# Generated by Django 4.2.19 on 2025-02-11 15:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PR_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PR_Documents',
            new_name='PR_Document',
        ),
    ]
