# Generated by Django 4.2.19 on 2025-02-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PR_App', '0002_rename_pr_documents_pr_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PR_Documents_Detail',
            new_name='PR_Document_Detail',
        ),
    ]
