# Generated by Django 4.2.19 on 2025-02-11 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PR_App', '0003_rename_pr_documents_detail_pr_document_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr_document_detail',
            name='pr_document',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='PR_App.pr_document'),
            preserve_default=False,
        ),
    ]
